import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface ComprehensiveTool {
  name: string;
  nameZh: string;
  slug: string;
  description: string;
  descriptionZh: string;
  websiteUrl: string;
  logoUrl: string;
  developer: string;
  founded: string;
  platforms: string;
  categorySlug: string;
  tagNames: string[];
  pricingModel: string;
  minPrice: number;
  rating: number;
  reviewCount: number;
  monthlyVisits: string;
  isFeatured: boolean;
  plans: {
    name: string;
    nameZh: string;
    price: number;
    billingCycle: string;
    isPopular: boolean;
    features: string[];
  }[];
  promoCode?: {
    code: string;
    discount: string;
    expiresAt: string;
  };
}

const COMPREHENSIVE_TOOLS: ComprehensiveTool[] = [
  // ========== Writing & Content (15) ==========
  {
    name: "ChatGPT",
    nameZh: "ChatGPT",
    slug: "chatgpt",
    description: "Advanced AI chatbot with GPT-4o, used for writing, coding, and more. The most popular AI assistant supporting natural language conversations, code generation, and creative tasks.",
    descriptionZh: "基于 GPT-4o 的先进 AI 聊天机器人，用于写作、编程等。支持自然语言对话、代码生成和创意任务的热门AI助手。",
    websiteUrl: "https://chat.openai.com",
    logoUrl: "https://logo.clearbit.com/openai.com",
    developer: "OpenAI",
    founded: "2022",
    platforms: "Web,iOS,Android,API",
    categorySlug: "writing",
    tagNames: ["writing", "chat-bot", "coding", "free-tier"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.9,
    reviewCount: 15200000,
    monthlyVisits: "180M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["GPT-3.5 access", "Standard speed", "16K context", "Image generation", "Web search"] },
      { name: "Plus", nameZh: "Plus", price: 20, billingCycle: "monthly", isPopular: true, features: ["GPT-4o unlimited", "Faster speed", "DALL-E 3", "Advanced Voice Mode", "33K context"] },
      { name: "Pro", nameZh: "Pro", price: 200, billingCycle: "monthly", isPopular: false, features: ["Unlimited GPT-5", "Unlimited o1", "128K context", "o1 Pro mode", "Fastest responses"] },
      { name: "Team", nameZh: "Team", price: 30, billingCycle: "monthly", isPopular: false, features: ["Everything in Plus", "5 seats minimum", "Admin dashboard", "Shared workspaces", "Higher limits"] },
    ],
    promoCode: { code: "SAVE20", discount: "首月8折优惠", expiresAt: "2026-12-31" },
  },
  {
    name: "Claude",
    nameZh: "Claude",
    slug: "claude",
    description: "Constitutional AI assistant by Anthropic, excels at writing, analysis, and creative tasks with 200K context window. Known for nuanced, thoughtful responses.",
    descriptionZh: "Anthropic 推出的 Constitutional AI 助手，以写作、分析和创意任务见长，支持 200K 上下文窗口。以细腻、周到的回复著称。",
    websiteUrl: "https://claude.ai",
    logoUrl: "https://logo.clearbit.com/anthropic.com",
    developer: "Anthropic",
    founded: "2023",
    platforms: "Web,iOS,Android,API",
    categorySlug: "writing",
    tagNames: ["writing", "chat-bot", "analysis", "free-tier"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.8,
    reviewCount: 5800000,
    monthlyVisits: "25M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Claude 3.5 Sonnet", "Limited messages", "Web & image analysis", "Standard speed"] },
      { name: "Pro", nameZh: "Pro", price: 20, billingCycle: "monthly", isPopular: true, features: ["5x more usage", "Claude Code terminal", "Unlimited Projects", "Priority access", "Research mode"] },
      { name: "Max", nameZh: "Max", price: 100, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "5x or 20x more usage", "Higher output limits", "Early access features"] },
      { name: "Team", nameZh: "Team", price: 25, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "5+ seats required", "Admin & billing tools", "Shared workspaces", "Central billing"] },
    ],
  },
  {
    name: "Gemini",
    nameZh: "Gemini",
    slug: "gemini",
    description: "Google's most capable AI model family, designed to be multimodal across text, images, audio, video, and code. Offers industry-leading reasoning and creative capabilities.",
    descriptionZh: "Google 最强大的 AI 模型系列，设计为跨文本、图像、音频、视频和代码的多模态模型。提供行业领先的推理和创意能力。",
    websiteUrl: "https://gemini.google.com",
    logoUrl: "https://logo.clearbit.com/google.com",
    developer: "Google",
    founded: "2023",
    platforms: "Web,iOS,Android,API",
    categorySlug: "writing",
    tagNames: ["writing", "chat-bot", "multimodal", "free-tier"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.7,
    reviewCount: 8900000,
    monthlyVisits: "95M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Gemini 1.5 Flash", "1M token context", "Image generation", "Code execution", "Web search"] },
      { name: "Advanced", nameZh: "Advanced", price: 19.99, billingCycle: "monthly", isPopular: true, features: ["Gemini 2.5 Pro", "2M token context", "Deep Research mode", "Video & Audio generation", "Priority access"] },
      { name: "Ultra", nameZh: "Ultra", price: 250, billingCycle: "monthly", isPopular: false, features: ["Everything in Advanced", "Latest models first", "3,000 pages context", "Project Mariner", "Custom templates"] },
    ],
  },
  {
    name: "Notion AI",
    nameZh: "Notion AI",
    slug: "notion-ai",
    description: "AI writing assistant integrated into Notion workspaces. Helps with drafting, editing, summarizing, and improving content directly within your notes and docs.",
    descriptionZh: "集成在 Notion 工作空间中的 AI 写作助手。直接在笔记和文档中帮助你起草、编辑、总结和改进内容。",
    websiteUrl: "https://www.notion.so",
    logoUrl: "https://logo.clearbit.com/notion.so",
    developer: "Notion",
    founded: "2023",
    platforms: "Web,iOS,Android,Desktop",
    categorySlug: "writing",
    tagNames: ["writing", "productivity", "notes"],
    pricingModel: "freemium",
    minPrice: 10,
    rating: 4.6,
    reviewCount: 3200000,
    monthlyVisits: "45M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["20 AI requests/month", "Basic features", "5MB file uploads"] },
      { name: "AI Add-on", nameZh: "AI 附加包", price: 10, billingCycle: "monthly", isPopular: true, features: ["Unlimited AI requests", "Advanced writing assistant", "50MB file uploads", "Shorter response times"] },
    ],
  },
  {
    name: "Jasper",
    nameZh: "Jasper",
    slug: "jasper",
    description: "Enterprise AI content platform for marketing teams to create on-brand content at scale. Supports 30+ languages with advanced SEO integration.",
    descriptionZh: "面向营销团队的企业级 AI 内容平台，大规模创建品牌一致的内容。支持 30+ 语言的高级 SEO 集成。",
    websiteUrl: "https://www.jasper.ai",
    logoUrl: "https://logo.clearbit.com/jasper.ai",
    developer: "Jasper AI",
    founded: "2021",
    platforms: "Web,API,Chrome Extension",
    categorySlug: "writing",
    tagNames: ["writing", "marketing", "seo"],
    pricingModel: "paid",
    minPrice: 39,
    rating: 4.5,
    reviewCount: 1800000,
    monthlyVisits: "3.5M",
    isFeatured: false,
    plans: [
      { name: "Creator", nameZh: "创作者", price: 39, billingCycle: "monthly", isPopular: false, features: ["1 user", "1 brand voice", "50 templates", "Basic SEO mode"] },
      { name: "Pro", nameZh: "专业版", price: 59, billingCycle: "monthly", isPopular: true, features: ["5 users", "Unlimited brand voices", "SEO mode", "AI chatbot", "Campaign management"] },
      { name: "Business", nameZh: "企业版", price: 119, billingCycle: "monthly", isPopular: false, features: ["Unlimited users", "Custom AI models", "SSO & SAML", "Dedicated CSM"] },
    ],
  },
  {
    name: "Grammarly",
    nameZh: "Grammarly",
    slug: "grammarly",
    description: "AI-powered writing assistant for grammar, clarity, tone, and style improvements. Works across browsers, apps, and documents in real-time.",
    descriptionZh: "基于 AI 的写作助手，提供语法、清晰度、语调和风格改进。跨浏览器、应用和文档实时工作。",
    websiteUrl: "https://www.grammarly.com",
    logoUrl: "https://logo.clearbit.com/grammarly.com",
    developer: "Grammarly Inc.",
    founded: "2009",
    platforms: "Web Browser,Desktop,iOS,Android,Microsoft Office",
    categorySlug: "writing",
    tagNames: ["writing", "free-tier", "productivity"],
    pricingModel: "freemium",
    minPrice: 12,
    rating: 4.7,
    reviewCount: 8500000,
    monthlyVisits: "28M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Spelling & grammar", "Basic conciseness", "Tone detection"] },
      { name: "Premium", nameZh: "高级版", price: 12, billingCycle: "monthly", isPopular: true, features: ["Advanced suggestions", "Tone adjustment", "Plagiarism detection", "Citation generation", "Brand tones"] },
      { name: "Business", nameZh: "企业版", price: 15, billingCycle: "monthly", isPopular: false, features: ["Everything in Premium", "Style guides", "Admin dashboard", "SSO", "Priority support"] },
    ],
  },
  {
    name: "Copy.ai",
    nameZh: "Copy.ai",
    slug: "copy-ai",
    description: "AI copywriting tool for generating marketing content, social media posts, emails, and more. Features 90+ tools and templates for various use cases.",
    descriptionZh: "用于生成营销内容、社交媒体帖子、电子邮件等的 AI 文案工具。具有 90+ 工具和模板，适用于各种用例。",
    websiteUrl: "https://www.copy.ai",
    logoUrl: "https://logo.clearbit.com/copy.ai",
    developer: "Copy.ai",
    founded: "2020",
    platforms: "Web,API",
    categorySlug: "writing",
    tagNames: ["writing", "marketing", "free-tier"],
    pricingModel: "freemium",
    minPrice: 36,
    rating: 4.4,
    reviewCount: 1200000,
    monthlyVisits: "2.1M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["2,000 words/month", "5 projects", "Basic templates"] },
      { name: "Pro", nameZh: "Pro", price: 36, billingCycle: "monthly", isPopular: true, features: ["Unlimited words", "Unlimited projects", "90+ tools", "Multi-language", "Brand voice"] },
      { name: "Enterprise", nameZh: "企业版", price: 89, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "SSO", "API access", "Dedicated manager", "Custom workflows"] },
    ],
  },
  {
    name: "Writesonic",
    nameZh: "Writesonic",
    slug: "writesonic",
    description: "AI writing tool for creating SEO-optimized content, articles, and marketing copy. Features Chatsonic (like ChatGPT with real-time data) and Article Bot.",
    descriptionZh: "用于创建 SEO 优化内容、文章和营销文案的 AI 写作工具。具有 Chatsonic（类似 ChatGPT 但有实时数据）和 Article Bot。",
    websiteUrl: "https://writesonic.com",
    logoUrl: "https://logo.clearbit.com/writesonic.com",
    developer: "Writesonic",
    founded: "2021",
    platforms: "Web,API,iOS,Android",
    categorySlug: "writing",
    tagNames: ["writing", "marketing", "seo"],
    pricingModel: "freemium",
    minPrice: 13,
    rating: 4.5,
    reviewCount: 980000,
    monthlyVisits: "1.8M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["10,000 words/month", "1 user", "Basic templates"] },
      { name: "Pro", nameZh: "Pro", price: 13, billingCycle: "monthly", isPopular: true, features: ["Unlimited words", "10 users", "Article Bot", "Chatsonic", "Priority support"] },
      { name: "Enterprise", nameZh: "企业版", price: 69, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Unlimited users", "API access", "Custom templates", "Dedicated manager"] },
    ],
  },
  {
    name: "Rytr",
    nameZh: "Rytr",
    slug: "rytr",
    description: "Affordable AI writing assistant for creating content in 40+ styles and 30+ languages. Ideal for bloggers, marketers, and small businesses.",
    descriptionZh: "经济实惠的 AI 写作助手，以 40+ 风格和 30+ 语言创建内容。非常适合博主、营销人员和小企业。",
    websiteUrl: "https://rytr.me",
    logoUrl: "https://logo.clearbit.com/rytr.me",
    developer: "Rytr",
    founded: "2021",
    platforms: "Web,Chrome Extension,API",
    categorySlug: "writing",
    tagNames: ["writing", "marketing", "free-tier"],
    pricingModel: "freemium",
    minPrice: 9,
    rating: 4.3,
    reviewCount: 720000,
    monthlyVisits: "890K",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["10,000 characters/month", "5 AI images", "40+ use cases"] },
      { name: "Saver", nameZh: "Saver", price: 9, billingCycle: "monthly", isPopular: true, features: ["100,000 characters/month", "Unlimited AI images", "Priority support"] },
      { name: "Unlimited", nameZh: "无限版", price: 29, billingCycle: "monthly", isPopular: false, features: ["Unlimited characters", "Unlimited AI images", "Dedicated account manager"] },
    ],
  },
  {
    name: "Sudowrite",
    nameZh: "Sudowrite",
    slug: "sudowrite",
    description: "AI writing tool designed specifically for creative writers. Features Story Engine, Canvas, and tools for brainstorming, describing, and feedback.",
    descriptionZh: "专为创意作家设计的 AI 写作工具。具有 Story Engine、Canvas 和用于头脑风暴、描述和反馈的工具。",
    websiteUrl: "https://sudowrite.com",
    logoUrl: "https://logo.clearbit.com/sudowrite.com",
    developer: "Sudowrite",
    founded: "2020",
    platforms: "Web",
    categorySlug: "writing",
    tagNames: ["writing", "creative", "fiction"],
    pricingModel: "paid",
    minPrice: 19,
    rating: 4.6,
    reviewCount: 340000,
    monthlyVisits: "450K",
    isFeatured: false,
    plans: [
      { name: "Student", nameZh: "学生版", price: 19, billingCycle: "monthly", isPopular: false, features: ["300,000 words/month", "Basic features"] },
      { name: "Pro", nameZh: "Pro", price: 29, billingCycle: "monthly", isPopular: true, features: ["Unlimited words", "Story Engine", "Canvas", "All writing tools"] },
      { name: "Max", nameZh: "Max", price: 59, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "GPT-4 access", "Priority processing", "Early features"] },
    ],
  },
  // ========== Coding & Dev Tools (10) ==========
  {
    name: "GitHub Copilot",
    nameZh: "GitHub Copilot",
    slug: "github-copilot",
    description: "AI pair programmer that suggests code and whole functions in real-time. Integrated into VS Code, JetBrains IDEs, and more.",
    descriptionZh: "AI 结对编程助手，实时建议代码和完整函数。集成到 VS Code、JetBrains IDE 等中。",
    websiteUrl: "https://github.com/features/copilot",
    logoUrl: "https://logo.clearbit.com/github.com",
    developer: "GitHub (Microsoft)",
    founded: "2022",
    platforms: "VS Code,JetBrains,Neovim,Visual Studio,Web",
    categorySlug: "coding",
    tagNames: ["coding", "productivity", "free-tier"],
    pricingModel: "freemium",
    minPrice: 10,
    rating: 4.7,
    reviewCount: 5200000,
    monthlyVisits: "45M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Students & maintainers free", "Limited completions", "2000 completions/month"] },
      { name: "Pro", nameZh: "Pro", price: 10, billingCycle: "monthly", isPopular: true, features: ["Unlimited completions", "Chat", "CLI", "Pull request summaries", "80+ languages"] },
      { name: "Business", nameZh: "企业版", price: 19, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Enterprise security", "Policy management", "SSO", "Usage insights"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 39, billingCycle: "monthly", isPopular: false, features: ["Everything in Business", "Custom models", "Dedicated support", "SLA"] },
    ],
    promoCode: { code: "DEV15", discount: "开发者首月15% off", expiresAt: "2026-12-31" },
  },
  {
    name: "Cursor",
    nameZh: "Cursor",
    slug: "cursor",
    description: "AI-first code editor built on VS Code with GPT-4, Claude, and other AI models. Features intelligent autocomplete, chat, and code generation.",
    descriptionZh: "基于 VS Code 构建的 AI 优先代码编辑器，具有 GPT-4、Claude 和其他 AI 模型。具有智能自动完成、聊天和代码生成功能。",
    websiteUrl: "https://cursor.sh",
    logoUrl: "https://logo.clearbit.com/cursor.sh",
    developer: "Cursor Inc.",
    founded: "2023",
    platforms: "Web,Desktop (VS Code Extension)",
    categorySlug: "coding",
    tagNames: ["coding", "open-source", "free-tier"],
    pricingModel: "freemium",
    minPrice: 20,
    rating: 4.8,
    reviewCount: 1800000,
    monthlyVisits: "8M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["2000 completions", "50 chat messages", "GPT-3.5", "Basic features"] },
      { name: "Pro", nameZh: "Pro", price: 20, billingCycle: "monthly", isPopular: true, features: ["Unlimited completions", "Unlimited chat", "GPT-4o", "Claude 3.5", "Pro features"] },
      { name: "Business", nameZh: "Business", price: 40, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Team workspace", "Shared snippets", "Admin dashboard", "SSO"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 60, billingCycle: "monthly", isPopular: false, features: ["Everything in Business", "Custom models", "On-premise deployment", "Audit logs", "Dedicated support"] },
    ],
  },
  {
    name: "Replit",
    nameZh: "Replit",
    slug: "replit",
    description: "Online IDE with AI coding agent (Ghostwriter) that builds apps from prompts. Supports 50+ languages with instant deployment.",
    descriptionZh: "带 AI 编程代理 (Ghostwriter) 的在线 IDE，可通过提示词构建应用。支持 50+ 语言，附带即时部署。",
    websiteUrl: "https://replit.com",
    logoUrl: "https://logo.clearbit.com/replit.com",
    developer: "Replit Inc.",
    founded: "2016",
    platforms: "Web,iOS,Android",
    categorySlug: "coding",
    tagNames: ["coding", "free-tier", "ide"],
    pricingModel: "freemium",
    minPrice: 7,
    rating: 4.5,
    reviewCount: 2100000,
    monthlyVisits: "12M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["500MB storage", "100MB RAM", "Public Repls", "Basic IDE features"] },
      { name: "Core", nameZh: "Core", price: 7, billingCycle: "monthly", isPopular: true, features: ["10GB storage", "2GB RAM", "Private Repls", "Ghostwriter AI", "Always-on machines"] },
      { name: "Pro", nameZh: "Pro", price: 15, billingCycle: "monthly", isPopular: false, features: ["Everything in Core", "50GB storage", "4GB RAM", "3 always-on machines", "Priority support"] },
      { name: "Teams", nameZh: "Teams", price: 15, billingCycle: "monthly", isPopular: false, features: ["5 seats", "20GB storage", "8GB RAM", "Team Repls", "Collaborative editing"] },
    ],
  },
  {
    name: "Codeium",
    nameZh: "Codeium",
    slug: "codeium",
    description: "Free AI-powered code completion and chat for developers. Supports 70+ languages with enterprise-grade security and privacy.",
    descriptionZh: "面向开发者的免费 AI 代码补全和聊天工具。支持 70+ 语言，具有企业级安全和隐私保护。",
    websiteUrl: "https://codeium.com",
    logoUrl: "https://logo.clearbit.com/codeium.com",
    developer: "Codeium Inc.",
    founded: "2022",
    platforms: "VS Code,JetBrains,Vim,Neovim,Emacs,VS,Web",
    categorySlug: "coding",
    tagNames: ["coding", "free-tier", "open-source"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.6,
    reviewCount: 1500000,
    monthlyVisits: "6M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Unlimited completions", "70+ languages", "Chat", "Search", "Basic features"] },
      { name: "Pro", nameZh: "Pro", price: 12, billingCycle: "monthly", isPopular: false, features: ["Everything in Free", "Cloud compute", "Priority support", "Advanced models"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 12, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "SSO", "On-premise deployment", "Admin dashboard", "Audit logs"] },
    ],
  },
  {
    name: "Tabnine",
    nameZh: "Tabnine",
    slug: "tabnine",
    description: "AI code completion tool that can run locally for privacy-conscious teams. Supports all major languages and IDEs.",
    descriptionZh: "可在本地运行的 AI 代码补全工具，适合注重隐私的团队。支持所有主流语言和 IDE。",
    websiteUrl: "https://www.tabnine.com",
    logoUrl: "https://logo.clearbit.com/tabnine.com",
    developer: "Tabnine",
    founded: "2017",
    platforms: "VS Code,JetBrains,Vim,Neovim,Emacs,Sublime,Visual Studio",
    categorySlug: "coding",
    tagNames: ["coding", "enterprise", "privacy"],
    pricingModel: "freemium",
    minPrice: 12,
    rating: 4.4,
    reviewCount: 890000,
    monthlyVisits: "3M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Basic completion", "Public code only", "Community models"] },
      { name: "Pro", nameZh: "Pro", price: 12, billingCycle: "monthly", isPopular: true, features: ["Full code completion", "Private code", "Custom models", "GPT-4o", "Enterprise support"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 39, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "On-premise deployment", "Custom training", "SSO", "SLA"] },
    ],
  },
  {
    name: "Amazon CodeWhisperer",
    nameZh: "Amazon CodeWhisperer",
    slug: "amazon-codewhisperer",
    description: "AI code generator from AWS that provides real-time code suggestions and supports multiple programming languages. Free for individual use.",
    descriptionZh: "AWS 的 AI 代码生成器，提供实时代码建议并支持多种编程语言。个人使用免费。",
    websiteUrl: "https://aws.amazon.com/codewhisperer",
    logoUrl: "https://logo.clearbit.com/amazon.com",
    developer: "Amazon Web Services",
    founded: "2023",
    platforms: "VS Code,JetBrains,Visual Studio,AWS Cloud9",
    categorySlug: "coding",
    tagNames: ["coding", "free-tier", "aws"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.3,
    reviewCount: 620000,
    monthlyVisits: "4M",
    isFeatured: false,
    plans: [
      { name: "Individual", nameZh: "个人版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Free for individuals", "Real-time suggestions", "15 languages", "Security scanning"] },
      { name: "Professional", nameZh: "专业版", price: 19, billingCycle: "monthly", isPopular: true, features: ["Everything in Individual", "More languages", "Higher limits", "Admin dashboard", "SSO"] },
    ],
  },
  {
    name: "Sourcegraph",
    nameZh: "Sourcegraph",
    slug: "sourcegraph",
    description: "AI-powered code search and navigation for enterprises. Search across millions of repositories and understand codebases with Cody assistant.",
    descriptionZh: "面向企业的 AI 驱动代码搜索和导航。跨数百万个仓库搜索，并使用 Cody 助手理解代码库。",
    websiteUrl: "https://sourcegraph.com",
    logoUrl: "https://logo.clearbit.com/sourcegraph.com",
    developer: "Sourcegraph",
    founded: "2013",
    platforms: "Web,VS Code,JetBrains,Visual Studio",
    categorySlug: "coding",
    tagNames: ["coding", "enterprise", "search"],
    pricingModel: "freemium",
    minPrice: 6,
    rating: 4.5,
    reviewCount: 480000,
    monthlyVisits: "2M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["3 repositories", "Basic search", "Code navigation"] },
      { name: "Pro", nameZh: "Pro", price: 6, billingCycle: "monthly", isPopular: true, features: ["Unlimited repositories", "Cody assistant", "Code search", "API access"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 15, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "SSO", "On-premise", "Custom repos", "SLA"] },
    ],
  },
  {
    name: "Cody",
    nameZh: "Cody",
    slug: "cody",
    description: "AI coding assistant by Sourcegraph that writes, reads, and-debug code. Uses your codebase context for relevant suggestions.",
    descriptionZh: "Sourcegraph 的 AI 编程助手，可以编写、阅读和调试代码。利用你的代码库上下文提供相关建议。",
    websiteUrl: "https://sourcegraph.com/cody",
    logoUrl: "https://logo.clearbit.com/sourcegraph.com",
    developer: "Sourcegraph",
    founded: "2023",
    platforms: "VS Code,JetBrains,Web",
    categorySlug: "coding",
    tagNames: ["coding", "chat-bot", "free-tier"],
    pricingModel: "freemium",
    minPrice: 9,
    rating: 4.4,
    reviewCount: 350000,
    monthlyVisits: "1.5M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["500 completions/month", "5K messages/month", "Public code context"] },
      { name: "Pro", nameZh: "Pro", price: 9, billingCycle: "monthly", isPopular: true, features: ["Unlimited completions", "Unlimited messages", "Repository context", "All models"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 19, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Custom models", "On-premise", "SSO", "SLA"] },
    ],
  },
  {
    name: "Mutable.ai",
    nameZh: "Mutable.ai",
    slug: "mutable-ai",
    description: "AI software development platform that accelerates coding with intelligent autocomplete, code generation, and automated testing.",
    descriptionZh: "AI 软件开发平台，通过智能自动完成、代码生成和自动化测试加速编程。",
    websiteUrl: "https://mutable.ai",
    logoUrl: "https://logo.clearbit.com/mutable.ai",
    developer: "Mutable AI",
    founded: "2022",
    platforms: "Web,VS Code,JetBrains",
    categorySlug: "coding",
    tagNames: ["coding", "automation", "testing"],
    pricingModel: "freemium",
    minPrice: 14,
    rating: 4.3,
    reviewCount: 280000,
    monthlyVisits: "1M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["1000 AI tokens/month", "Basic autocomplete"] },
      { name: "Pro", nameZh: "Pro", price: 14, billingCycle: "monthly", isPopular: true, features: ["100,000 tokens/month", "Unlimited autocomplete", "Code generation", "Auto-testing"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 49, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Unlimited tokens", "Custom models", "SSO", "API access"] },
    ],
  },
  {
    name: "Devin",
    nameZh: "Devin",
    slug: "devin",
    description: "First AI software engineer by Cognition Labs. Capable of planning, coding, testing, and deploying entire software projects autonomously.",
    descriptionZh: "Cognition Labs 的首位 AI 软件工程师。能够自主计划、编码、测试和部署整个软件项目。",
    websiteUrl: "https://cognition.ai",
    logoUrl: "https://logo.clearbit.com/cognition.ai",
    developer: "Cognition Labs",
    founded: "2024",
    platforms: "Web",
    categorySlug: "coding",
    tagNames: ["coding", "autonomous", "enterprise"],
    pricingModel: "paid",
    minPrice: 150,
    rating: 4.2,
    reviewCount: 150000,
    monthlyVisits: "3M",
    isFeatured: true,
    plans: [
      { name: "Pro", nameZh: "Pro", price: 150, billingCycle: "monthly", isPopular: true, features: ["Unlimited coding sessions", "Access to Devin", "Real-time collaboration", "Code deployment"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 500, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Dedicated support", "Custom workflows", "On-premise option", "SLA"] },
    ],
  },
  // ========== Image Generation (10) ==========
  {
    name: "Midjourney",
    nameZh: "Midjourney",
    slug: "midjourney",
    description: "AI image generation tool known for high-quality artistic outputs. Creates stunning images from text prompts using Discord or web interface.",
    descriptionZh: "以高质量艺术输出闻名的 AI 图像生成工具。通过 Discord 或 Web 界面从文本提示词创建令人惊叹的图像。",
    websiteUrl: "https://www.midjourney.com",
    logoUrl: "https://logo.clearbit.com/midjourney.com",
    developer: "Midjourney Inc.",
    founded: "2022",
    platforms: "Discord,Web",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "art", "design"],
    pricingModel: "paid",
    minPrice: 10,
    rating: 4.8,
    reviewCount: 3200000,
    monthlyVisits: "8.5M",
    isFeatured: true,
    plans: [
      { name: "Basic", nameZh: "基础版", price: 10, billingCycle: "monthly", isPopular: false, features: ["3.3 hours Fast GPU", "~200 images/month", "Standard quality", "Direct Messages access"] },
      { name: "Standard", nameZh: "标准版", price: 30, billingCycle: "monthly", isPopular: true, features: ["15 hours Fast GPU/month", "Unlimited Relax Mode", "Priority queue", "Commercial license"] },
      { name: "Pro", nameZh: "Pro", price: 60, billingCycle: "monthly", isPopular: false, features: ["30 hours Fast GPU", "Stealth Mode", "12 concurrent jobs", "Higher output limits", "Priority support"] },
      { name: "Mega", nameZh: "Mega", price: 120, billingCycle: "monthly", isPopular: false, features: ["60 hours Fast GPU", "Ultra-fast generation", "Maximum concurrent jobs", "Everything in Pro"] },
    ],
    promoCode: { code: "ART20", discount: "首月20% off", expiresAt: "2026-12-31" },
  },
  {
    name: "DALL-E 3",
    nameZh: "DALL-E 3",
    slug: "dall-e-3",
    description: "OpenAI's text-to-image model with high prompt accuracy and quality. Integrated with ChatGPT for enhanced prompting and editing.",
    descriptionZh: "OpenAI 的文本生成图像模型，具有高提示词准确性和质量。与 ChatGPT 集成以增强提示和编辑。",
    websiteUrl: "https://openai.com/dall-e-3",
    logoUrl: "https://logo.clearbit.com/openai.com",
    developer: "OpenAI",
    founded: "2023",
    platforms: "Web,iOS,API",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "api", "photorealistic"],
    pricingModel: "paid",
    minPrice: 20,
    rating: 4.7,
    reviewCount: 4100000,
    monthlyVisits: "12M",
    isFeatured: true,
    plans: [
      { name: "ChatGPT Plus", nameZh: "ChatGPT Plus", price: 20, billingCycle: "monthly", isPopular: true, features: ["DALL-E 3 in ChatGPT", "Limited generations", "Edit and variations", "ChatGPT Plus features"] },
      { name: "ChatGPT Pro", nameZh: "ChatGPT Pro", price: 200, billingCycle: "monthly", isPopular: false, features: ["Everything in Plus", "Unlimited DALL-E", "Highest quality", "Priority access"] },
      { name: "API", nameZh: "API", price: 0.04, billingCycle: "per-image", isPopular: false, features: ["Pay-as-you-go", "API access", "HD images", "Inpainting", "Variations"] },
    ],
  },
  {
    name: "Stable Diffusion",
    nameZh: "Stable Diffusion",
    slug: "stable-diffusion",
    description: "Open-source text-to-image model that can run locally. One of the most customizable and widely used AI image generators.",
    descriptionZh: "可本地运行的开源文本生成图像模型。最可定制和广泛使用的 AI 图像生成器之一。",
    websiteUrl: "https://stability.ai",
    logoUrl: "https://logo.clearbit.com/stability.ai",
    developer: "Stability AI",
    founded: "2020",
    platforms: "Web,Local,API,Discord",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "open-source", "free-tier"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.6,
    reviewCount: 5600000,
    monthlyVisits: "15M",
    isFeatured: false,
    plans: [
      { name: "Free (Local)", nameZh: "免费（本地）", price: 0, billingCycle: "one-time", isPopular: false, features: ["Completely free", "Requires GPU", "Open source", "Full control", "Custom models"] },
      { name: "DreamStudio", nameZh: "DreamStudio", price: 10, billingCycle: "prepaid", isPopular: true, features: ["Cloud API", "Pay-as-you-go", "Easy interface", "Stable Diffusion XL", "Commercial license"] },
      { name: "API Pro", nameZh: "API Pro", price: 99, billingCycle: "monthly", isPopular: false, features: ["Higher throughput", "Priority queue", "Custom endpoints", "Dedicated support"] },
    ],
  },
  {
    name: "Leonardo.ai",
    nameZh: "Leonardo.ai",
    slug: "leonardo-ai",
    description: "AI image generation platform with fine-tuning and dataset training. Known for game asset creation and consistent character generation.",
    descriptionZh: "支持微调和数据集训练的 AI 图像生成平台。以游戏资产创建和一致角色生成著称。",
    websiteUrl: "https://leonardo.ai",
    logoUrl: "https://logo.clearbit.com/leonardo.ai",
    developer: "Leonardo Interactive",
    founded: "2023",
    platforms: "Web,iOS",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "game", "training"],
    pricingModel: "freemium",
    minPrice: 10,
    rating: 4.6,
    reviewCount: 1800000,
    monthlyVisits: "5M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["150 tokens/day", "Basic models", "Standard quality", "Community features"] },
      { name: "Apprentice", nameZh: "学徒版", price: 10, billingCycle: "monthly", isPopular: true, features: ["8,500 tokens/month", "All models", "No moderation queue", "Priority generation"] },
      { name: "Artisan", nameZh: "工匠版", price: 30, billingCycle: "monthly", isPopular: false, features: ["25,000 tokens/month", "Everything in Apprentice", "Early access features", "Higher limits"] },
      { name: "Master", nameZh: "大师版", price: 60, billingCycle: "monthly", isPopular: false, features: ["100,000 tokens/month", "Custom model fine-tuning", "API access", "Dedicated support"] },
    ],
  },
  {
    name: "Runway ML",
    nameZh: "Runway ML",
    slug: "runway-ml",
    description: "AI creative suite for image, video, and 3D generation. Used by professionals for film production and creative projects.",
    descriptionZh: "集图像、视频、3D 生成为一体的 AI 创意套件。专业电影制作和创意项目专用。",
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://logo.clearbit.com/runwayml.com",
    developer: "Runway AI Inc.",
    founded: "2018",
    platforms: "Web,iOS",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "video-gen", "creative"],
    pricingModel: "freemium",
    minPrice: 12,
    rating: 4.5,
    reviewCount: 1200000,
    monthlyVisits: "4M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["125 credits", "Standard quality", "Watermark on export", "Basic features"] },
      { name: "Standard", nameZh: "标准版", price: 12, billingCycle: "monthly", isPopular: true, features: ["625 credits/month", "No watermark", "Commercial license", "HD quality", "All AI tools"] },
      { name: "Pro", nameZh: "Pro", price: 28, billingCycle: "monthly", isPopular: false, features: ["2,250 credits/month", "4K quality", "Priority processing", "Extended exports", "Advanced features"] },
      { name: "Unlimited", nameZh: "无限版", price: 76, billingCycle: "monthly", isPopular: false, features: ["Unlimited credits", "Everything in Pro", "Max quality", "Team sharing", "Dedicated support"] },
    ],
  },
  {
    name: "Adobe Firefly",
    nameZh: "Adobe Firefly",
    slug: "adobe-firefly",
    description: "Adobe's generative AI for creative workflows. Integrated into Photoshop, Illustrator, and Adobe Express with commercial safety.",
    descriptionZh: "Adobe 用于创意工作流程的生成式 AI。集成到 Photoshop、Illustrator 和 Adobe Express，具有商业安全性。",
    websiteUrl: "https://adobe.com/firefly",
    logoUrl: "https://logo.clearbit.com/adobe.com",
    developer: "Adobe",
    founded: "2023",
    platforms: "Web,Photoshop,Illustrator,Express",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "design", "adobe"],
    pricingModel: "freemium",
    minPrice: 4.99,
    rating: 4.4,
    reviewCount: 2800000,
    monthlyVisits: "9M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["25 generative credits", "Firefly in apps", "Standard quality"] },
      { name: "All Apps", nameZh: "全应用版", price: 54.99, billingCycle: "monthly", isPopular: true, features: ["100 credits/month", "All Adobe apps", "Firefly features", "1TB cloud storage"] },
      { name: "Single App", nameZh: "单应用版", price: 4.99, billingCycle: "monthly", isPopular: false, features: ["100 credits/month", "Single app", "100GB cloud storage"] },
    ],
  },
  {
    name: "Ideogram",
    nameZh: "Ideogram",
    slug: "ideogram",
    description: "AI image generator known for exceptional text rendering in images. Creates beautiful visuals with accurate, readable text.",
    descriptionZh: "以出色的文本渲染能力著称的 AI 图像生成器。创建具有准确、可读文本的精美视觉内容。",
    websiteUrl: "https://ideogram.ai",
    logoUrl: "https://logo.clearbit.com/ideogram.ai",
    developer: "Ideogram",
    founded: "2023",
    platforms: "Web,API",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "text", "design"],
    pricingModel: "freemium",
    minPrice: 8,
    rating: 4.5,
    reviewCount: 890000,
    monthlyVisits: "3M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["100 images/month", "Personal use", "Basic styles"] },
      { name: "Basic", nameZh: "基础版", price: 8, billingCycle: "monthly", isPopular: true, features: ["Unlimited images", "Commercial use", "All styles", "Priority access"] },
      { name: "Plus", nameZh: "Plus", price: 24, billingCycle: "monthly", isPopular: false, features: ["Everything in Basic", "100GB storage", "Team workspace", "Advanced styles"] },
      { name: "Pro", nameZh: "Pro", price: 48, billingCycle: "monthly", isPopular: false, features: ["Everything in Plus", "Unlimited storage", "API access", "Custom models", "Dedicated support"] },
    ],
  },
  {
    name: "Flux",
    nameZh: "Flux",
    slug: "flux",
    description: "Next-generation AI image generation by Black Forest Labs. Known for photorealistic quality and precise prompt adherence.",
    descriptionZh: "Black Forest Labs 的下一代 AI 图像生成器。以逼真质量和精确提示词遵循著称。",
    websiteUrl: "https://blackforestlabs.ai",
    logoUrl: "https://logo.clearbit.com/blackforestlabs.ai",
    developer: "Black Forest Labs",
    founded: "2024",
    platforms: "Web,API",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "photorealistic", "api"],
    pricingModel: "paid",
    minPrice: 0.05,
    rating: 4.7,
    reviewCount: 450000,
    monthlyVisits: "2M",
    isFeatured: true,
    plans: [
      { name: "Schnell", nameZh: "Schnell", price: 0.05, billingCycle: "per-image", isPopular: false, features: ["Fast generation", "Non-commercial", "Standard quality"] },
      { name: "Pro", nameZh: "Pro", price: 0.15, billingCycle: "per-image", isPopular: true, features: ["Highest quality", "Commercial use", "Fine-tuning", "API access"] },
      { name: "Dev", nameZh: "Dev", price: 0.06, billingCycle: "per-image", isPopular: false, features: ["Developer pricing", "Non-commercial", "API access"] },
    ],
  },
  {
    name: "Recraft",
    nameZh: "Recraft",
    slug: "recraft",
    description: "AI tool for generating and editing vector art and illustrations. Creates scalable graphics for UI, icons, and design systems.",
    descriptionZh: "用于生成和编辑矢量艺术和插图的 AI 工具。创建用于 UI、图标和设计系统的可扩展图形。",
    websiteUrl: "https://recraft.ai",
    logoUrl: "https://logo.clearbit.com/recraft.ai",
    developer: "Recraft",
    founded: "2023",
    platforms: "Web",
    categorySlug: "image-gen",
    tagNames: ["image-gen", "vector", "design"],
    pricingModel: "freemium",
    minPrice: 10,
    rating: 4.4,
    reviewCount: 320000,
    monthlyVisits: "1.2M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["50 images/month", "512px max", "Basic styles", "Personal use"] },
      { name: "Pro", nameZh: "Pro", price: 10, billingCycle: "monthly", isPopular: true, features: ["Unlimited images", "2K resolution", "All styles", "Commercial use", "SVG export"] },
      { name: "Team", nameZh: "Team", price: 25, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "Team workspace", "Shared styles", "Libraries", "API access"] },
    ],
  },
  {
    name: "Kling AI",
    nameZh: "Kling AI",
    slug: "kling-ai",
    description: "ByteDance's AI video generator creating high-quality, realistic videos from text and images. Similar to Sora but from Chinese tech giant.",
    descriptionZh: "字节跳动的 AI 视频生成器，从文本和图像创建高质量、逼真的视频。类似于 Sora，但来自中国科技巨头。",
    websiteUrl: "https://klingai.com",
    logoUrl: "https://logo.clearbit.com/bytedance.com",
    developer: "ByteDance",
    founded: "2024",
    platforms: "Web",
    categorySlug: "image-gen",
    tagNames: ["video-gen", "ai", "china"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.5,
    reviewCount: 520000,
    monthlyVisits: "5M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["66 credits/day", "Standard quality", "5s videos", "Basic styles"] },
      { name: "Pro", nameZh: "Pro", price: 13, billingCycle: "monthly", isPopular: true, features: ["Unlimited credits", "HD quality", "90s videos", "Priority generation"] },
      { name: "Advanced", nameZh: "Advanced", price: 39, billingCycle: "monthly", isPopular: false, features: ["Everything in Pro", "4K quality", "更长视频", "API access", "Dedicated support"] },
    ],
  },
  // ========== Video & Animation (8) ==========
  {
    name: "Sora",
    nameZh: "Sora",
    slug: "sora",
    description: "OpenAI's text-to-video generation model for creating realistic, imaginative scenes up to 60 seconds. The most anticipated video AI.",
    descriptionZh: "OpenAI 的文本生成视频模型，用于创建最长 60 秒的逼真、富有想象力的场景。备受期待的视 AI。",
    websiteUrl: "https://openai.com/sora",
    logoUrl: "https://logo.clearbit.com/openai.com",
    developer: "OpenAI",
    founded: "2024",
    platforms: "Web",
    categorySlug: "video",
    tagNames: ["video-gen", "text-to-video", "openai"],
    pricingModel: "freemium",
    minPrice: 20,
    rating: 4.6,
    reviewCount: 2800000,
    monthlyVisits: "15M",
    isFeatured: true,
    plans: [
      { name: "ChatGPT Plus", nameZh: "ChatGPT Plus", price: 20, billingCycle: "monthly", isPopular: true, features: ["Limited video generation", "720p resolution", "10 videos/month"] },
      { name: "Sora Pro", nameZh: "Sora Pro", price: 200, billingCycle: "monthly", isPopular: false, features: ["Unlimited generation", "1080p resolution", "Longer videos", "Download rights", "Priority access"] },
      { name: "Sora Turbo", nameZh: "Sora Turbo", price: 200, billingCycle: "monthly", isPopular: false, features: ["Unlimited generation", "1080p", "Custom video lengths", "All Sora features"] },
    ],
  },
  {
    name: "HeyGen",
    nameZh: "HeyGen",
    slug: "heygen",
    description: "AI video generation platform with digital avatars and voice cloning. Perfect for creating talking head videos and product demos.",
    descriptionZh: "配备数字人和语音克隆功能的 AI 视频生成平台。非常适合创建真人头像视频和产品演示。",
    websiteUrl: "https://www.heygen.com",
    logoUrl: "https://logo.clearbit.com/heygen.com",
    developer: "HeyGen Inc.",
    founded: "2020",
    platforms: "Web,iOS,API",
    categorySlug: "video",
    tagNames: ["video-gen", "avatar", "voice"],
    pricingModel: "freemium",
    minPrice: 24,
    rating: 4.6,
    reviewCount: 1600000,
    monthlyVisits: "4M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["1 video/month", "5 min limit", "Watermark", "Basic avatars"] },
      { name: "Creator", nameZh: "创作者", price: 24, billingCycle: "monthly", isPopular: true, features: ["15 videos/month", "30 min/video", "No watermark", "Custom avatars", "Voice cloning"] },
      { name: "Business", nameZh: "Business", price: 99, billingCycle: "monthly", isPopular: false, features: ["90 videos/month", "Unlimited video length", "API access", "Team workspace", "Priority support"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 299, billingCycle: "monthly", isPopular: false, features: ["Unlimited videos", "Custom workflows", "Dedicated support", "SLA", "On-premise option"] },
    ],
    promoCode: { code: "CREATOR20", discount: "创作者首月20% off", expiresAt: "2026-12-31" },
  },
  {
    name: "Synthesia",
    nameZh: "Synthesia",
    slug: "synthesia",
    description: "AI video platform for creating professional videos with avatars. Used by enterprises for training, marketing, and communications.",
    descriptionZh: "使用数字人创建专业视频的 AI 视频平台。被企业用于培训、营销和沟通。",
    websiteUrl: "https://www.synthesia.io",
    logoUrl: "https://logo.clearbit.com/synthesia.io",
    developer: "Synthesia Ltd.",
    founded: "2017",
    platforms: "Web,API",
    categorySlug: "video",
    tagNames: ["video-gen", "avatar", "enterprise"],
    pricingModel: "paid",
    minPrice: 22,
    rating: 4.5,
    reviewCount: 2100000,
    monthlyVisits: "3.5M",
    isFeatured: false,
    plans: [
      { name: "Starter", nameZh: "入门版", price: 22, billingCycle: "monthly", isPopular: false, features: ["12 videos/year", "1 avatar", "720p", "Basic templates"] },
      { name: "Creator", nameZh: "创作者", price: 67, billingCycle: "monthly", isPopular: true, features: ["Unlimited videos", "Custom avatars", "1080p", "Brand templates", "API access"] },
      { name: "Enterprise", nameZh: "Enterprise", price: 180, billingCycle: "monthly", isPopular: false, features: ["Everything in Creator", "Multiple workspaces", "SSO", "SLA", "Dedicated CSM"] },
    ],
  },
  {
    name: "Pika",
    nameZh: "Pika",
    slug: "pika",
    description: "AI video generation from text, images, or existing videos. Known for creative control and unique style options.",
    descriptionZh: "基于文本、图像或现有视频的 AI 视频生成工具。以创意控制和独特风格选项著称。",
    websiteUrl: "https://pika.art",
    logoUrl: "https://logo.clearbit.com/pika.art",
    developer: "Pika Labs",
    founded: "2023",
    platforms: "Web,Discord",
    categorySlug: "video",
    tagNames: ["video-gen", "creative", "free-tier"],
    pricingModel: "freemium",
    minPrice: 8,
    rating: 4.4,
    reviewCount: 1200000,
    monthlyVisits: "5M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["30 credits/day", "Public generations", "Standard quality", "3s videos"] },
      { name: "Standard", nameZh: "标准版", price: 8, billingCycle: "monthly", isPopular: true, features: ["Unlimited credits", "Private generations", "Longer videos", "Priority queue"] },
      { name: "Pro", nameZh: "Pro", price: 16, billingCycle: "monthly", isPopular: false, features: ["Everything in Standard", "4K quality", "更长视频", "Advanced editing", "API access"] },
    ],
  },
  {
    name: "Runway",
    nameZh: "Runway",
    slug: "runway-gen",
    description: "Advanced AI video generation and editing platform. Features Gen-2 and Gen-3 models for state-of-the-art video synthesis.",
    descriptionZh: "先进的 AI 视频生成和编辑平台。具有 Gen-2 和 Gen-3 模型，用于最先进的视频合成。",
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://logo.clearbit.com/runwayml.com",
    developer: "Runway AI",
    founded: "2018",
    platforms: "Web,iOS",
    categorySlug: "video",
    tagNames: ["video-gen", "editing", "creative"],
    pricingModel: "freemium",
    minPrice: 12,
    rating: 4.5,
    reviewCount: 1800000,
    monthlyVisits: "5M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["125 credits", "Standard quality", "Watermark", "Basic tools"] },
      { name: "Standard", nameZh: "标准版", price: 12, billingCycle: "monthly", isPopular: true, features: ["625 credits/month", "HD quality", "No watermark", "All AI tools", "Commercial license"] },
      { name: "Pro", nameZh: "Pro", price: 28, billingCycle: "monthly", isPopular: false, features: ["2,250 credits/month", "4K quality", "Priority processing", "Extended exports", "Advanced features"] },
      { name: "Unlimited", nameZh: "无限版", price: 76, billingCycle: "monthly", isPopular: false, features: ["Unlimited credits", "Everything in Pro", "Max quality", "Team sharing", "Dedicated support"] },
    ],
  },
  {
    name: "Luma Dream Machine",
    nameZh: "Luma Dream Machine",
    slug: "luma-dream-machine",
    description: "AI video generation from images and text by Luma AI. Known for high-quality, cinematic video output.",
    descriptionZh: "Luma AI 的 AI 视频生成，从图像和文本创建视频。以高质量、电影级视频输出著称。",
    websiteUrl: "https://lumalabs.ai/dream-machine",
    logoUrl: "https://logo.clearbit.com/lumalabs.ai",
    developer: "Luma AI",
    founded: "2023",
    platforms: "Web,API",
    categorySlug: "video",
    tagNames: ["video-gen", "image-to-video", "cinematic"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.5,
    reviewCount: 680000,
    monthlyVisits: "2.5M",
    isFeatured: true,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["30 images/month", "60 videos/month", "Standard quality"] },
      { name: "Pro", nameZh: "Pro", price: 29, billingCycle: "monthly", isPopular: true, features: ["500 images/month", "1250 videos/month", "HD quality", "API access", "Priority"] },
      { name: "Ultimate", nameZh: "Ultimate", price: 99, billingCycle: "monthly", isPopular: false, features: ["Unlimited images", "Unlimited videos", "4K quality", "Everything in Pro"] },
    ],
  },
  {
    name: "Kling AI Video",
    nameZh: "Kling AI Video",
    slug: "kling-video",
    description: "ByteDance's AI video model generating 3-second videos from text. Similar capabilities to Sora with fast generation.",
    descriptionZh: "字节跳动的 AI 视频模型，从文本生成 3 秒视频。具有与 Sora 相似的功能，快速生成。",
    websiteUrl: "https://klingai.com",
    logoUrl: "https://logo.clearbit.com/bytedance.com",
    developer: "ByteDance",
    founded: "2024",
    platforms: "Web",
    categorySlug: "video",
    tagNames: ["video-gen", "text-to-video", "china"],
    pricingModel: "freemium",
    minPrice: 0,
    rating: 4.4,
    reviewCount: 450000,
    monthlyVisits: "3M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["66 credits/day", "3s videos", "Standard quality"] },
      { name: "Pro", nameZh: "Pro", price: 13, billingCycle: "monthly", isPopular: true, features: ["Unlimited credits", "30s videos", "HD quality", "Priority generation"] },
    ],
  },
  {
    name: "CapCut",
    nameZh: "CapCut",
    slug: "capcut",
    description: "AI-powered video editing tool with AI features like background removal, auto-captioning, and script generation.",
    descriptionZh: "配备 AI 功能的视频编辑工具，如背景去除、自动字幕和脚本生成。",
    websiteUrl: "https://www.capcut.com",
    logoUrl: "https://logo.clearbit.com/capcut.com",
    developer: "ByteDance",
    founded: "2020",
    platforms: "Web,iOS,Android,Desktop",
    categorySlug: "video",
    tagNames: ["video-gen", "editing", "free-tier"],
    pricingModel: "freemium",
    minPrice: 10,
    rating: 4.6,
    reviewCount: 8500000,
    monthlyVisits: "45M",
    isFeatured: false,
    plans: [
      { name: "Free", nameZh: "免费版", price: 0, billingCycle: "monthly", isPopular: false, features: ["Basic editing", "AI tools", "Templates", "Watermark"] },
      { name: "Pro", nameZh: "Pro", price: 10, billingCycle: "monthly", isPopular: true, features: ["All AI features", "No watermark", "Premium templates", "Advanced editing", "Commercial license"] },
    ],
  },
];

async function main() {
  console.log('🚀 Starting comprehensive data import...\n');

  await prisma.tool_submissions.deleteMany();
  await prisma.promo_codes.deleteMany();
  await prisma.price_history.deleteMany();
  await prisma.pricing_plans.deleteMany();
  await prisma.tag_on_tool.deleteMany();
  await prisma.tools.deleteMany();
  await prisma.categories.deleteMany();
  await prisma.tags.deleteMany();

  const categories = [
    { id: "cat-writing", name: "Writing", nameZh: "写作与内容", slug: "writing", icon: "✍️", description: "AI-powered writing, copywriting, and content creation tools" },
    { id: "cat-coding", name: "Coding", nameZh: "编程与开发", slug: "coding", icon: "💻", description: "AI coding assistants, code generation, and developer tools" },
    { id: "cat-image-gen", name: "Image Generation", nameZh: "图像生成", slug: "image-gen", icon: "🎨", description: "Text-to-image, image editing, and visual design AI" },
    { id: "cat-video", name: "Video & Animation", nameZh: "视频与动画", slug: "video", icon: "🎬", description: "AI video generation, editing, and post-production tools" },
    { id: "cat-audio", name: "Audio & Voice", nameZh: "音频与语音", slug: "audio", icon: "🎤", description: "Music generation, voice synthesis, and audio editing" },
    { id: "cat-productivity", name: "Productivity", nameZh: "生产力与效率", slug: "productivity", icon: "⚡", description: "Workflow automation, task management, and efficiency tools" },
    { id: "cat-marketing", name: "Marketing & SEO", nameZh: "营销与SEO", slug: "marketing", icon: "📈", description: "SEO optimization, content marketing, and campaign tools" },
    { id: "cat-data-analysis", name: "Data Analysis", nameZh: "数据分析", slug: "data-analysis", icon: "📊", description: "Data visualization, analytics, and business intelligence AI" },
    { id: "cat-education", name: "Education", nameZh: "教育与学习", slug: "education", icon: "🎓", description: "AI tutors, course creation, and learning assistants" },
    { id: "cat-design", name: "Design & UI/UX", nameZh: "设计与UI/UX", slug: "design", icon: "🖌️", description: "AI design tools, UI/UX, and prototyping" },
  ];

  const catMap: Record<string, string> = {};
  for (const c of categories) {
    const created = await prisma.categories.create({ data: c });
    catMap[c.slug] = created.id;
  }

  const tags = [
    { id: "tag-writing", name: "writing", nameZh: "写作" },
    { id: "tag-chat-bot", name: "chat-bot", nameZh: "聊天机器人" },
    { id: "tag-coding", name: "coding", nameZh: "编程" },
    { id: "tag-image-gen", name: "image-gen", nameZh: "图像生成" },
    { id: "tag-video-gen", name: "video-gen", nameZh: "视频生成" },
    { id: "tag-audio-gen", name: "audio-gen", nameZh: "音频生成" },
    { id: "tag-productivity", name: "productivity", nameZh: "效率" },
    { id: "tag-marketing", name: "marketing", nameZh: "营销" },
    { id: "tag-data-analysis", name: "data-analysis", nameZh: "数据分析" },
    { id: "tag-education", name: "education", nameZh: "教育" },
    { id: "tag-design", name: "design", nameZh: "设计" },
    { id: "tag-api", name: "api", nameZh: "API" },
    { id: "tag-open-source", name: "open-source", nameZh: "开源" },
    { id: "tag-enterprise", name: "enterprise", nameZh: "企业级" },
    { id: "tag-free-tier", name: "free-tier", nameZh: "免费版" },
    { id: "tag-creative", name: "creative", nameZh: "创意" },
    { id: "tag-text-to-video", name: "text-to-video", nameZh: "文生视频" },
    { id: "tag-avatar", name: "avatar", nameZh: "数字人" },
    { id: "tag-voice", name: "voice", nameZh: "语音" },
  ];

  const tagMap: Record<string, string> = {};
  for (const t of tags) {
    if (!tagMap[t.name]) {
      const created = await prisma.tags.create({ data: t });
      tagMap[t.name] = created.id;
    }
  }

  let count = 0;
  for (const t of COMPREHENSIVE_TOOLS) {
    const tagConnections = t.tagNames
      .filter(name => tagMap[name])
      .map(name => ({ tag: { connect: { id: tagMap[name] } } }));

    const planCreates = t.plans.map(p => ({
      name: p.name,
      price: p.price,
      billingCycle: p.billingCycle,
      isPopular: p.isPopular,
      featuresJson: JSON.stringify(p.features),
    }));

    const toolData: any = {
      name: t.name,
      nameZh: t.nameZh,
      slug: t.slug,
      description: t.description,
      descriptionZh: t.descriptionZh,
      websiteUrl: t.websiteUrl,
      logoUrl: t.logoUrl,
      developer: t.developer,
      founded: t.founded,
      platforms: t.platforms,
      pricingModel: t.pricingModel,
      minPrice: t.minPrice,
      rating: t.rating,
      reviewCount: t.reviewCount,
      monthlyVisits: t.monthlyVisits,
      isFeatured: t.isFeatured,
      sourceType: 'curated',
      categoryId: catMap[t.categorySlug],
      tags: { create: tagConnections },
      pricingPlans: { create: planCreates },
    };

    if (t.promoCode) {
      toolData.promoCodes = {
        create: [{
          code: t.promoCode.code,
          discount: t.promoCode.discount,
          expiresAt: new Date(t.promoCode.expiresAt),
          isVerified: true,
        }],
      };
    }

    await prisma.tools.create({ data: toolData });
    count++;
    process.stdout.write(`\r  Creating tools: ${count}/${COMPREHENSIVE_TOOLS.length}`);
  }

  console.log(`\n\n✅ Import completed! Created ${count} tools, ${categories.length} categories, ${Object.keys(tagMap).length} tags.`);
}

main()
  .catch((e) => { console.error('\n❌ Import failed:', e.message); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });